### ISSUE TITLE
Icon for Signal Private Messenger

### ISSUE THREAD

**Issue by edgard** [numixproject/circle-core#3436] opened 2016-10-05 15:06 UTC
Chrome App:

https://chrome.google.com/webstore/detail/signal-private-messenger/bikioccmkafdpakkkcpdbppfkghcmihk

**Comment by gregorydk** [comment] 2016-10-07 12:02
Duplicate of https://github.com/numixproject/circle-core/issues/2997

**Comment by Foggalong** [comment] 2016-10-07 16:59
@gregorydk Good catch!

**Closed by Foggalong** 2016-10-07 16:59 UTC
Labels: duplicate
