### ISSUE TITLE
Icon for FreeCAD

### ISSUE THREAD

**Issue by leebickmtu** [numixproject/circle-core#3378] opened 2016-08-17 08:40 UTC
An icon for FreeCAD is missing.
The icon line says "/usr/share/freecad/freecad.xpm".
The original icon is attached.

![freecad-icon-48](https://cloud.githubusercontent.com/assets/7145871/17729999/b50a1f64-6434-11e6-868f-9b9136f5442f.png)

**Comment by leebickmtu** [comment] 2016-08-17 11:12
I made this icon for it quickly, uses an axonometric coordinate axis in the middle (common view mode in FreeCAD).

[custom_freecad_2.svg](https://drive.google.com/open?id=0B-LiD1ANXy-MVmpRWlZqcE1wVDQ)

**Comment by palob** [comment] 2016-08-17 11:35
duplicate of #939 

The icon is hardcoded. You need to modify the ```.desktop`` launcher file or use the hardcode-fixer, cf. https://github.com/numixproject/circle-core#hardcoded-icons

**Closed** 2016-08-19 23:14 UTC
Labels: duplicate
