### ISSUE TITLE
Ubuntu Logout, Shutdown and Reboot menu app icons

### ISSUE THREAD

**Issue by szekeres2016** [numixproject/circle-core#3364] opened 2016-08-08 17:59 UTC
Good day, the most notably out of size icons left untouched by the theme are the new Logout, Shutdown and Reboot icons added with the 16.04 release. The icons are hardcoded unfortunately:

Logout file name is "logout.desktop"
"Icon=/usr/share/unity/icons/logout_highlight.png"

Reboot file name is "reboot.desktop"
"Icon=/usr/share/unity/icons/restart_highlight.png"

Shutdown file name is "shutdown.desktop"
"Icon=/usr/share/unity/icons/shutdown_highlight.png"

**Comment by palob** [comment] 2016-08-09 10:28
duplicate of #2967 # 2968 #2969

**Closed** 2016-08-10 14:59 UTC
Labels: duplicate
