### ISSUE TITLE
Ubuntu logout, shutdown and reboot icons

### ISSUE THREAD

**Issue by leoheck** [numixproject/circle-core#3367] opened 2016-08-09 13:20 UTC
Can these icons be replaced? It will be nice to have better icons.

![selection_004](https://cloud.githubusercontent.com/assets/1277920/17517664/bb569e62-5e1a-11e6-8f9f-f00821f83cb8.png)

**Comment by palob** [comment] 2016-08-09 14:42
duplicate of #2967 #2968 #2969 #3364

**Comment by leoheck** [comment] 2016-08-09 19:26
Oh my god! Sorry :pray: 
The first and second were closed, so the icons are already available?
So, what are the name of these icons? I have to ask them in the hardcode-fixer. 
Thanks

**Comment by palob** [comment] 2016-08-09 21:06
The issues are tagged *wontfix* since the reasoning behind having those action as app launchers was questioned.

I think it is quite the travesty the Ubuntu people don't seem to be able to adhere to ``freedesktop.org`` standards.

Fair enough, maybe it was the intern so I'll cut some slack :-)

**Closed** 2016-08-10 14:59 UTC
Labels: duplicate
