### ISSUE TITLE
Icon for GitKraken

### ISSUE THREAD

**Issue by leebickmtu** [numixproject/circle-core#3379] opened 2016-08-17 08:49 UTC
An icon for GitKraken is missing.
The icon line says "gitkraken".
The original icon is attached.

![app](https://cloud.githubusercontent.com/assets/7145871/17730225/dbc8cf00-6435-11e6-86f9-a7b156fc2e28.png)

**Comment by palob** [comment] 2016-08-17 11:40
duplicate of #2880 but not hardcoded.

**Closed** 2016-08-19 23:16 UTC
Labels: duplicate
